### PR TITLE
 mayhem integration

### PR DESCRIPTION
**Pull request by evanrichter**

### CODE REVIEW

**Review by xansec — APPROVED** [review]
LGTM!

**Comment by xansec** [comment]
@evanrichter Do you mind looking at this run? It seems to either be always crashing or something wrong with error handling in the harness:
https://mayhem.forallsecure.com/mayhemheroes/img-hash/image-hashing/2

**Comment by evanrichter** [comment]
the crash is reporting an error at this subtraction, which is causing integer wrapping:

https://github.com/mayhemheroes/img_hash/blob/0147fe153029033ad697f3f0b47b88bc4704ed1c/src/traits.rs#L183

I'm unclear if wrapping behavior is intended or not, but in rust normal arithmetic is assumed to never wrap, and it should be changed to

```rs
        self.iter_mut().zip(other.iter()).for_each(|(l, r)| *l = l.wrapping_sub(*r));
```

**Comment by xansec** [comment]
We're still getting coverage post crash, so I think ok to leave for now, and maybe request upstream to resolve at a later point.

**Pull request merged**
